In [48]:
import numpy as np
import pandas as pd
import re

seed= 42

In [49]:
train_df= pd.read_csv('train.csv')
test_df= pd.read_csv('test.csv')

X_train= train_df['text']
y_train= train_df['label']

X_test= test_df['text']

In [50]:
# Subtask 1

answer1= pd.DataFrame([{
    'subtaskID': 1,
    'datapointID': id_,
    'answer': len(text)
}for id_, text  in zip(test_df['sample_id'],test_df['text'])])

answer1.head()

   subtaskID  datapointID  answer
0          1        75707     237
1          1         4026     946
2          1         2156    1554
3          1        49593    1207
4          1        23028    1684

In [51]:
# Subtask 2

answer2= pd.DataFrame([{
    'subtaskID': 2,
    'datapointID': id_,
    'answer': len(re.findall(r'\bfree\b', text, flags=re.IGNORECASE))
}for id_, text  in zip(test_df['sample_id'],test_df['text'])])

answer2.head()

   subtaskID  datapointID  answer
0          2        75707       0
1          2         4026       0
2          2         2156       1
3          2        49593       0
4          2        23028       0

In [52]:
# Subtask 3

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.svm import LinearSVC

cv= CountVectorizer()

X_train= cv.fit_transform(X_train)
X_test= cv.transform(X_test)

model= LinearSVC(max_iter=1000)

model.fit(X_train, y_train)

predictions= model.predict(X_test)

/media/aeru1/HDD/Problems/AI/AI_Problems/NLP/nlp_env/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

In [53]:
answer3= pd.DataFrame([{
    'subtaskID': 3,
    'datapointID': id_,
    'answer': pred
}for id_, pred  in zip(test_df['sample_id'], predictions)])

answer3.head()

   subtaskID  datapointID  answer
0          3        75707       1
1          3         4026       0
2          3         2156       1
3          3        49593       0
4          3        23028       1

In [54]:
answer= pd.concat([answer1, answer2, answer3])
answer.to_csv("submission.csv", index= False)